export const teamMembers = [
    {
     name: "Anna Kovalchuk",
position:"Team Lead",
link:"https://github.com/kovAnya",
img_jpg: "/AnnaKovalchyk.jpg",
img_webp:"/AnnaKovalchyk.webp",   
    },
    {
     name:"Anna Rakarchuk",
position:"Scrum Master",
link:"https://github.com/AnnaRakarchuk",
img_jpg: "/Anna.jpg",
img_webp:"/Anna.webp",  
    },
        {
     name:"Denys Yevdokymenko",
position:"Developer",
link:"https://github.com/Yevdokymenko",
img_jpg: "/DenysYevdokymenko.jpg",
img_webp:"/DenysYevdokymenko.webp",   
    },
        {
     name:"Olha Chornei",
position:"Developer",
link:"https://github.com/Chornei-Olha",
img_jpg: "/Olha.jpg",
img_webp:"/Olha.webp",   
    },
        {
     name:"Oleksandr Berdychevskyi",
position:"Developer",
link:"https://github.com/Oleksandr-Berd",
img_jpg: "/OleksandrDerdychevcskyi.jpg",
img_webp:"/OleksandrDerdychevcskyi.webp",   
    },
        {
     name:"Viktor Ponomarev",
position:"Developer",
link:"https://github.com/ViktorPonomarev",
img_jpg: "/ViktorPonomarev.jpg",
img_webp:"/ViktorPonomarev.webp",     
    },
        {
     name:"Oleksandr Suprunyuk",
position:"Developer",
link:"https://github.com/suprunyuk-a",
img_jpg: "/Suprunyuk.jpg",
img_webp:"/Suprunyuk.webp",    
    },
        {
     name:"Dima Kuzmich",
position:"Developer",
link:"https://github.com/Kuzmich87",
img_jpg: "/DimaKuzmich.jpg",
img_webp:"/DimaKuzmich.webp",    
    },
        {
     name:"Dima Shapoval",
position:"Developer",
link:"https://github.com/Dzybystim",
img_jpg: "/DimaShapoval.jpg",
img_webp:"/DimaShapoval.webp",   
    },
        {
     name:"Kostya Zavaliy",
position:"Developer",
link:"https://github.com/Kostya2700",
img_jpg: "/kostya.jpg",
img_webp:"/kostya.webp",     
    },
    {
name:"Valeriia Volkova",
position:"Developer",
link: "https://github.com/vvolk-valeria",
img_jpg: "/Valeria.jpg",
img_webp:"/Valeria.webp",   
    }
]